name: checkIn
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  schedule:
    - cron: 30 1 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: install axios
        run: npm install axios
      - name: CheckIn
        run: node checkin.js
        env:
          plusToken: ${{ secrets.plusToken }}
          COOKIES: ${{ secrets.COOKIES }}
      - name: keep alive
        uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
